-- =====================================================================
-- GAMES feature update
-- รันไฟล์นี้ใน Supabase SQL Editor (Dashboard > SQL Editor > New query)
-- ปลอดภัยที่จะรันซ้ำ (idempotent)
--   1) ตัวละครที่ผู้เล่นเลือกได้ (admin อัปโหลดรูป)
--   2) รูปด่าน (map icon) บนหน้าเลือกด่าน
--   3) เวลาตอบแยกระหว่างโจทย์แบบเลือกตอบ กับ โจทย์เรียงประโยค
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. game_characters : ตัวละครให้ผู้เล่นเลือก (cosmetic avatar)
--    ค่าพลังเริ่มต้นเท่ากันทุกตัว (อัปเกรดด้วย EXP ผ่านระบบ shop เดิม)
-- ---------------------------------------------------------------------
create table if not exists public.game_characters (
  id bigint generated by default as identity primary key,
  name text not null,
  image_url text not null,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.game_characters enable row level security;

drop policy if exists game_characters_read on public.game_characters;
create policy game_characters_read on public.game_characters
  for select to authenticated using (true);

drop policy if exists game_characters_admin_write on public.game_characters;
create policy game_characters_admin_write on public.game_characters
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ---------------------------------------------------------------------
-- 2. user_game_state : เก็บตัวละครที่ผู้เล่นเลือก
-- ---------------------------------------------------------------------
alter table public.user_game_state
  add column if not exists selected_character_id bigint
  references public.game_characters(id) on delete set null;

-- ---------------------------------------------------------------------
-- 3. game_stages : เวลาตอบเกมเรียงประโยค (แยกจากแบบเลือกตอบ) + รูปด่าน
-- ---------------------------------------------------------------------
alter table public.game_stages
  add column if not exists answer_time_rearrange_sec integer not null default 12;

alter table public.game_stages
  add column if not exists map_image_url text;

-- ---------------------------------------------------------------------
-- 4. user_game_state : เลเวลผู้เล่น (Level UP เมื่อฆ่า Boss ในแต่ละด่าน)
-- ---------------------------------------------------------------------
alter table public.user_game_state
  add column if not exists level integer not null default 1;

-- ---------------------------------------------------------------------
-- 5. user_game_state : อาวุธที่เลือกนำไปต่อสู้ (สูงสุด 3 ช่อง)
--    เก็บเป็น jsonb array ของ item_id เช่น [3, 4]
-- ---------------------------------------------------------------------
alter table public.user_game_state
  add column if not exists equipped_item_ids jsonb not null default '[]'::jsonb;

-- RPC: เพิ่มเลเวลแบบ atomic (คืน row ใหม่ของ user_game_state)
create or replace function public.level_up_game(p_amount integer default 1)
returns public.user_game_state
language plpgsql
security definer
as $$
declare
  result public.user_game_state;
begin
  insert into public.user_game_state (user_id, level, updated_at)
  values (auth.uid(), 1 + greatest(p_amount, 0), now())
  on conflict (user_id) do update
    set level = public.user_game_state.level + greatest(p_amount, 0),
        updated_at = now()
  returning * into result;
  return result;
end;
$$;

-- ---------------------------------------------------------------------
-- 6. user_upgrades : ซื้ออัปเกรดตัวละครซ้ำได้ (สะสมจำนวน)
--    เดิมซื้อได้ครั้งเดียวต่อรายการ ตอนนี้เก็บ quantity เพื่อสะสมผล
--    เช่น "หัวใจเพิ่ม +1" ซื้อ 3 ครั้ง = +3 HP
-- ---------------------------------------------------------------------
alter table public.user_upgrades
  add column if not exists quantity integer not null default 1;

-- ---------------------------------------------------------------------
-- 7. game_stages : ปรับระบบด่านใหม่
--    - เพิ่มด่านได้ไม่จำกัด (เดิมจำกัด 1-5)
--    - ไม่ผูกคำกับ flashcard level อีกต่อไป (เดิม source_level 3-7)
--      คำในแต่ละด่านจะแบ่งจาก "Select Study Words" ตามลำดับ
--      ด่านละ (monster_count + 1) คำ = มอนสเตอร์ + บอส
--    - ตั้งค่ามอนสเตอร์เริ่มต้นเป็น 30 ตัว
-- ---------------------------------------------------------------------
alter table public.game_stages drop constraint if exists game_stages_stage_no_check;
alter table public.game_stages drop constraint if exists game_stages_source_level_check;
alter table public.game_stages alter column source_level drop not null;
alter table public.game_stages alter column monster_count set default 30;
