-- =====================================================================
-- GAMES Battle Mode - Database Schema
-- รันไฟล์นี้ใน Supabase SQL Editor (Dashboard > SQL Editor > New query)
-- ปลอดภัยที่จะรันซ้ำ (idempotent) เพราะใช้ IF NOT EXISTS / ON CONFLICT
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. เพิ่มคอลัมน์ is_admin ในตาราง profiles
-- ---------------------------------------------------------------------
alter table public.profiles add column if not exists is_admin boolean not null default false;

-- ฟังก์ชันช่วยเช็คว่าเป็น admin (ใช้ใน RLS policy)
create or replace function public.is_admin()
returns boolean
language sql
security definer
stable
as $$
  select coalesce(
    (select p.is_admin from public.profiles p where p.user_id = auth.uid()),
    false
  );
$$;

-- ---------------------------------------------------------------------
-- 2. user_game_state : EXP / Coin ต่อผู้ใช้
-- ---------------------------------------------------------------------
create table if not exists public.user_game_state (
  user_id uuid primary key references auth.users(id) on delete cascade,
  exp integer not null default 0,
  coin integer not null default 0,
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- 3. exp_rewards : EXP ที่ได้รับต่อ LV ของ Flashcards (ข้อ 2.8)
-- ---------------------------------------------------------------------
create table if not exists public.exp_rewards (
  flashcard_level integer primary key check (flashcard_level between 1 and 7),
  exp_amount integer not null default 10
);

insert into public.exp_rewards (flashcard_level, exp_amount) values
  (1, 5), (2, 5), (3, 10), (4, 15), (5, 20), (6, 25), (7, 30)
on conflict (flashcard_level) do nothing;

-- ---------------------------------------------------------------------
-- 4. game_stages : การตั้งค่าด่าน (ข้อ 2.4 เวลาตอบต่อด่าน)
-- ---------------------------------------------------------------------
create table if not exists public.game_stages (
  stage_no integer primary key check (stage_no between 1 and 5),
  source_level integer not null check (source_level between 3 and 7),
  answer_time_sec integer not null default 8,
  monster_count integer not null default 3,
  title text
);

insert into public.game_stages (stage_no, source_level, answer_time_sec, monster_count, title) values
  (1, 3, 8, 3, 'ด่าน 1'),
  (2, 4, 8, 3, 'ด่าน 2'),
  (3, 5, 7, 4, 'ด่าน 3'),
  (4, 6, 7, 4, 'ด่าน 4'),
  (5, 7, 6, 5, 'ด่าน 5')
on conflict (stage_no) do nothing;

-- ---------------------------------------------------------------------
-- 5. game_backgrounds : รูปพื้นหลังต่อด่าน (หลายรูป สุ่มแสดง) (ข้อ 2.1)
-- ---------------------------------------------------------------------
create table if not exists public.game_backgrounds (
  id bigint generated by default as identity primary key,
  stage_no integer not null references public.game_stages(stage_no) on delete cascade,
  image_url text not null,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- 6. game_enemies : Monster / Boss + HP + พลังโจมตี (ข้อ 2.2, 2.3)
-- ---------------------------------------------------------------------
create table if not exists public.game_enemies (
  id bigint generated by default as identity primary key,
  stage_no integer not null references public.game_stages(stage_no) on delete cascade,
  type text not null check (type in ('monster', 'boss')),
  name text,
  image_url text not null,
  hp integer not null default 3,
  attack integer not null default 1,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- 7. game_music : เพลงประจำด่าน (หลายเพลง สุ่มเล่น) (ข้อ 2.5)
-- ---------------------------------------------------------------------
create table if not exists public.game_music (
  id bigint generated by default as identity primary key,
  stage_no integer not null references public.game_stages(stage_no) on delete cascade,
  music_url text not null,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- 8. game_sfx : Sound effect ต่อท่าโจมตี/เหตุการณ์ (ข้อ 2.6)
--    key เช่น: player_attack, enemy_attack, hit, win, lose, item, lucky_draw, hub_music
-- ---------------------------------------------------------------------
create table if not exists public.game_sfx (
  key text primary key,
  audio_url text not null
);

-- ---------------------------------------------------------------------
-- 9. shop_items : ไอเทม + อัปเกรด (ข้อ 2.7, 5)
--    kind: 'upgrade' (ถาวร ใช้ EXP) | 'item' (ใช้แล้วหมด ใช้ Coin)
--    effect_type: add_hp | add_attack | heal | shield
-- ---------------------------------------------------------------------
create table if not exists public.shop_items (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  icon_url text,
  kind text not null check (kind in ('upgrade', 'item')),
  currency text not null check (currency in ('exp', 'coin')),
  cost integer not null default 0,
  effect_type text not null check (effect_type in ('add_hp', 'add_attack', 'heal', 'shield')),
  effect_value integer not null default 1,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- ข้อมูลตั้งต้น (สามารถแก้/ลบในหน้า Admin ได้)
insert into public.shop_items (name, description, kind, currency, cost, effect_type, effect_value, sort_order) values
  ('หัวใจเพิ่ม +1', 'เพิ่ม HP สูงสุดถาวร 1 หัวใจ', 'upgrade', 'exp', 50, 'add_hp', 1, 1),
  ('ดาบเหล็ก', 'เพิ่มพลังโจมตีถาวร +1', 'upgrade', 'exp', 80, 'add_attack', 1, 2),
  ('ยาฟื้นพลัง', 'ฟื้น HP 1 หัวใจระหว่างต่อสู้', 'item', 'coin', 20, 'heal', 1, 3),
  ('โล่ป้องกัน', 'กันการโจมตีครั้งถัดไป 1 ครั้ง', 'item', 'coin', 30, 'shield', 1, 4)
on conflict do nothing;

-- ---------------------------------------------------------------------
-- 10. user_upgrades : อัปเกรดถาวรที่ผู้ใช้ซื้อแล้ว
-- ---------------------------------------------------------------------
create table if not exists public.user_upgrades (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  item_id bigint not null references public.shop_items(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, item_id)
);

-- ---------------------------------------------------------------------
-- 11. user_items : ไอเทมใช้แล้วหมด (inventory)
-- ---------------------------------------------------------------------
create table if not exists public.user_items (
  user_id uuid not null references auth.users(id) on delete cascade,
  item_id bigint not null references public.shop_items(id) on delete cascade,
  quantity integer not null default 0,
  primary key (user_id, item_id)
);

-- =====================================================================
-- RLS Policies
-- =====================================================================
alter table public.user_game_state enable row level security;
alter table public.exp_rewards enable row level security;
alter table public.game_stages enable row level security;
alter table public.game_backgrounds enable row level security;
alter table public.game_enemies enable row level security;
alter table public.game_music enable row level security;
alter table public.game_sfx enable row level security;
alter table public.shop_items enable row level security;
alter table public.user_upgrades enable row level security;
alter table public.user_items enable row level security;

-- config tables: อ่านได้ทุกคนที่ login, เขียนได้เฉพาะ admin
do $$
declare
  t text;
begin
  foreach t in array array['exp_rewards','game_stages','game_backgrounds','game_enemies','game_music','game_sfx','shop_items']
  loop
    execute format('drop policy if exists %I_read on public.%I', t, t);
    execute format('create policy %I_read on public.%I for select to authenticated using (true)', t, t);
    execute format('drop policy if exists %I_admin_write on public.%I', t, t);
    execute format('create policy %I_admin_write on public.%I for all to authenticated using (public.is_admin()) with check (public.is_admin())', t, t);
  end loop;
end $$;

-- user-owned tables: อ่าน/เขียนเฉพาะเจ้าของ
drop policy if exists user_game_state_own on public.user_game_state;
create policy user_game_state_own on public.user_game_state
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists user_upgrades_own on public.user_upgrades;
create policy user_upgrades_own on public.user_upgrades
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists user_items_own on public.user_items;
create policy user_items_own on public.user_items
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

-- =====================================================================
-- RPC: เพิ่ม EXP / Coin แบบ atomic (กันค่าหายเมื่อแก้พร้อมกัน)
-- =====================================================================
create or replace function public.add_game_currency(p_exp integer, p_coin integer)
returns public.user_game_state
language plpgsql
security definer
as $$
declare
  result public.user_game_state;
begin
  insert into public.user_game_state (user_id, exp, coin, updated_at)
  values (auth.uid(), greatest(p_exp, 0), greatest(p_coin, 0), now())
  on conflict (user_id) do update
    set exp = public.user_game_state.exp + greatest(p_exp, 0),
        coin = public.user_game_state.coin + greatest(p_coin, 0),
        updated_at = now()
  returning * into result;
  return result;
end;
$$;

-- RPC: หักเงินเพื่อซื้อของ (คืน true ถ้าสำเร็จ)
create or replace function public.spend_game_currency(p_currency text, p_amount integer)
returns boolean
language plpgsql
security definer
as $$
declare
  ok boolean := false;
begin
  if p_currency = 'exp' then
    update public.user_game_state
      set exp = exp - p_amount, updated_at = now()
      where user_id = auth.uid() and exp >= p_amount;
    ok := found;
  elsif p_currency = 'coin' then
    update public.user_game_state
      set coin = coin - p_amount, updated_at = now()
      where user_id = auth.uid() and coin >= p_amount;
    ok := found;
  end if;
  return ok;
end;
$$;

-- =====================================================================
-- Storage bucket สำหรับไฟล์เกม (public read, admin write)
-- =====================================================================
insert into storage.buckets (id, name, public)
values ('game-assets', 'game-assets', true)
on conflict (id) do nothing;

drop policy if exists "game-assets public read" on storage.objects;
create policy "game-assets public read" on storage.objects
  for select to public using (bucket_id = 'game-assets');

drop policy if exists "game-assets admin write" on storage.objects;
create policy "game-assets admin write" on storage.objects
  for all to authenticated
  using (bucket_id = 'game-assets' and public.is_admin())
  with check (bucket_id = 'game-assets' and public.is_admin());

-- =====================================================================
-- ตั้งให้ตัวเองเป็น admin (แก้ค่าอีเมลให้ตรงกับ user ของคุณ)
-- ตัวอย่าง: update public.profiles set is_admin = true where email = 'admin@nihao.com';
-- =====================================================================
