-- =====================================================================
-- LUCKY DRAW - ระบบสุ่มแจกรางวัลประจำวัน
-- รันไฟล์นี้ใน Supabase SQL Editor (Dashboard > SQL Editor > New query)
-- ปลอดภัยที่จะรันซ้ำ (idempotent)
--
-- แนวคิด:
--   - สุ่มที่ฝั่ง Server (RPC) เพื่อกันรีเฟรชโกง/กดรับซ้ำ
--   - สุ่ม 2 ชั้น: (1) สุ่มระดับความหายาก common/rare/epic ตามน้ำหนัก
--                  (2) สุ่มของในระดับนั้นตามน้ำหนักของแต่ละชิ้น
--   - แจกได้เฉพาะ COIN และ item ใช้แล้วหมด (shop_items.kind = 'item')
--   - รับได้วันละ 1 ครั้ง (รีเซ็ตเที่ยงคืนเวลาไทย Asia/Bangkok)
--   - Streak: รับติดกันทุกวันจะนับต่อเนื่อง ครบรอบ (ค่าเริ่มต้น 7 วัน)
--             การันตีได้ของระดับ epic
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1) game_settings : ตารางตั้งค่ารวม (สร้างให้ถ้ายังไม่มี — ไม่ต้องรัน player_stat_caps.sql ก่อน)
--    แถวเดียว id = 1 — ใช้ร่วมกับเพดานพลังผู้เล่น + น้ำหนัก Lucky Draw
-- ---------------------------------------------------------------------
create table if not exists public.game_settings (
  id integer primary key default 1,
  player_max_hp integer not null default 15,
  player_max_attack integer not null default 5,
  updated_at timestamptz not null default now(),
  constraint game_settings_singleton check (id = 1)
);

insert into public.game_settings (id, player_max_hp, player_max_attack)
values (1, 15, 5)
on conflict (id) do nothing;

alter table public.game_settings enable row level security;

drop policy if exists game_settings_read on public.game_settings;
create policy game_settings_read on public.game_settings
  for select to authenticated using (true);

drop policy if exists game_settings_admin_write on public.game_settings;
create policy game_settings_admin_write on public.game_settings
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- คอลัมน์ Lucky Draw (เพิ่มทีหลังถ้ายังไม่มี)
alter table public.game_settings
  add column if not exists lucky_common_weight integer not null default 65;
alter table public.game_settings
  add column if not exists lucky_rare_weight integer not null default 28;
alter table public.game_settings
  add column if not exists lucky_epic_weight integer not null default 7;
alter table public.game_settings
  add column if not exists lucky_epic_streak_days integer not null default 7;

-- ---------------------------------------------------------------------
-- 2) user_settings : วันที่รับล่าสุด + จำนวนวันต่อเนื่อง (streak)
-- ---------------------------------------------------------------------
alter table public.user_settings
  add column if not exists last_lucky_draw_date date;
alter table public.user_settings
  add column if not exists lucky_draw_streak integer not null default 0;

-- ---------------------------------------------------------------------
-- 3) lucky_draw_prizes : คลังรางวัลในกล่องสุ่ม (admin แก้ได้)
--    tier        = ระดับความหายาก (common | rare | epic)
--    reward_type = coin | item
--    coin_amount = จำนวน COIN (ใช้เมื่อ reward_type = 'coin')
--    item_id     = อ้างถึง shop_items (ใช้เมื่อ reward_type = 'item')
--    item_qty    = จำนวนไอเทมที่แจก
--    weight      = น้ำหนักการสุ่มภายใน tier เดียวกัน (มาก= ออกบ่อย)
--    label       = ชื่อที่แสดงบนการ์ดรางวัล (ไม่ใส่ก็ได้ จะ fallback อัตโนมัติ)
-- ---------------------------------------------------------------------
create table if not exists public.lucky_draw_prizes (
  id bigint generated by default as identity primary key,
  tier text not null check (tier in ('common', 'rare', 'epic')),
  reward_type text not null check (reward_type in ('coin', 'item')),
  coin_amount integer not null default 0,
  item_id bigint references public.shop_items(id) on delete cascade,
  item_qty integer not null default 1,
  weight integer not null default 1 check (weight >= 0),
  label text,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  -- รางวัลที่เป็นไอเทมต้องระบุ item_id เสมอ
  constraint lucky_prize_item_ref check (reward_type <> 'item' or item_id is not null)
);

-- =====================================================================
-- RLS: อ่านได้ทุกคนที่ login, เขียนได้เฉพาะ admin
-- =====================================================================
alter table public.lucky_draw_prizes enable row level security;

drop policy if exists lucky_draw_prizes_read on public.lucky_draw_prizes;
create policy lucky_draw_prizes_read on public.lucky_draw_prizes
  for select to authenticated using (true);

drop policy if exists lucky_draw_prizes_admin_write on public.lucky_draw_prizes;
create policy lucky_draw_prizes_admin_write on public.lucky_draw_prizes
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- =====================================================================
-- 4) RPC: lucky_draw_status — เช็คสถานะ (วันนี้รับหรือยัง + streak)
--    ใช้วันที่ฝั่ง server (เวลาไทย) เพื่อให้ตรงกับตอนกดรับ
-- =====================================================================
create or replace function public.lucky_draw_status()
returns json
language plpgsql
security definer
as $$
declare
  v_uid uuid := auth.uid();
  v_today date := (now() at time zone 'Asia/Bangkok')::date;
  v_last date;
  v_streak integer := 0;
  v_cycle integer;
begin
  if v_uid is null then
    return json_build_object('ok', false, 'error', 'not_authenticated');
  end if;

  select last_lucky_draw_date, coalesce(lucky_draw_streak, 0)
    into v_last, v_streak
  from public.user_settings
  where user_id = v_uid;

  -- ถ้าขาดวัน (ไม่ได้รับเมื่อวาน) streak ที่จะนับต่อจะรีเซ็ตเป็น 0 สำหรับการแสดงผล
  if v_last is null or v_last < v_today - 1 then
    v_streak := 0;
  end if;

  select coalesce(lucky_epic_streak_days, 7) into v_cycle
  from public.game_settings where id = 1;

  return json_build_object(
    'ok', true,
    'claimed_today', (v_last = v_today),
    'streak', coalesce(v_streak, 0),
    'epic_cycle', coalesce(v_cycle, 7),
    'server_date', v_today
  );
end;
$$;

-- =====================================================================
-- 5) RPC: claim_lucky_draw — กดรับรางวัลประจำวัน (atomic)
--    ขั้นตอน:
--      1. จองสิทธิ์ของวันนี้แบบ atomic (กันกดซ้ำ/รีเฟรชโกง)
--      2. คำนวณ streak ใหม่
--      3. สุ่มระดับ (หรือการันตี epic เมื่อครบรอบ streak)
--      4. สุ่มรางวัลในระดับนั้นตามน้ำหนัก
--      5. จ่ายรางวัล (COIN หรือ item) เข้าบัญชีผู้เล่น
--    ทั้งหมดอยู่ใน transaction เดียว: ถ้าพลาดกลางทางจะ rollback ทั้งหมด
-- =====================================================================
create or replace function public.claim_lucky_draw()
returns json
language plpgsql
security definer
as $$
declare
  v_uid uuid := auth.uid();
  v_today date := (now() at time zone 'Asia/Bangkok')::date;
  v_streak integer;
  v_common integer; v_rare integer; v_epic integer;
  v_cycle integer;
  v_tier text;
  v_total integer;
  v_r integer;
  v_wtotal integer;
  v_pick integer;
  v_guaranteed boolean := false;
  v_prize public.lucky_draw_prizes;
  v_item public.shop_items;
  v_new_coin integer;
begin
  if v_uid is null then
    return json_build_object('ok', false, 'error', 'not_authenticated');
  end if;

  -- ให้แน่ใจว่ามีแถว user_settings
  insert into public.user_settings (user_id) values (v_uid)
  on conflict (user_id) do nothing;

  -- (1) จองสิทธิ์ของวันนี้แบบ atomic + คำนวณ streak ในคำสั่งเดียว
  --     ถ้าแถวถูกอัปเดตเป็นวันนี้ไปแล้ว (รับไปแล้ว) update จะไม่ match → not found
  update public.user_settings
    set last_lucky_draw_date = v_today,
        lucky_draw_streak = case
          when last_lucky_draw_date = v_today - 1 then coalesce(lucky_draw_streak, 0) + 1
          else 1
        end
    where user_id = v_uid
      and (last_lucky_draw_date is distinct from v_today);

  if not found then
    return json_build_object('ok', false, 'already_claimed', true);
  end if;

  select lucky_draw_streak into v_streak
  from public.user_settings where user_id = v_uid;

  -- (2) อ่านน้ำหนักระดับจากตั้งค่ารวม
  select coalesce(lucky_common_weight, 65),
         coalesce(lucky_rare_weight, 28),
         coalesce(lucky_epic_weight, 7),
         coalesce(lucky_epic_streak_days, 7)
    into v_common, v_rare, v_epic, v_cycle
  from public.game_settings where id = 1;

  v_common := coalesce(v_common, 65);
  v_rare := coalesce(v_rare, 28);
  v_epic := coalesce(v_epic, 7);
  v_cycle := coalesce(v_cycle, 7);

  -- (3) ครบรอบ streak → การันตี epic, ไม่งั้นสุ่มระดับตามน้ำหนัก
  if v_cycle > 0 and v_streak % v_cycle = 0 then
    v_tier := 'epic';
    v_guaranteed := true;
  else
    v_total := greatest(v_common + v_rare + v_epic, 1);
    v_r := floor(random() * v_total);
    if v_r < v_common then
      v_tier := 'common';
    elsif v_r < v_common + v_rare then
      v_tier := 'rare';
    else
      v_tier := 'epic';
    end if;
  end if;

  -- (4) สุ่มรางวัลในระดับที่ได้ตามน้ำหนัก — ถ้าระดับนั้นไม่มีของ ให้สุ่มจากทุกระดับ
  select sum(weight) into v_wtotal
  from public.lucky_draw_prizes
  where active and weight > 0 and tier = v_tier;

  if coalesce(v_wtotal, 0) <= 0 then
    v_tier := null; -- fallback: สุ่มจากของที่เปิดใช้งานทั้งหมด
    select sum(weight) into v_wtotal
    from public.lucky_draw_prizes
    where active and weight > 0;
  end if;

  if coalesce(v_wtotal, 0) <= 0 then
    -- ไม่มีรางวัลเลย → rollback การจองสิทธิ์ด้วยการ raise
    raise exception 'no_active_prizes';
  end if;

  v_pick := floor(random() * v_wtotal) + 1; -- 1..v_wtotal

  select p.* into v_prize
  from (
    select lp.*, sum(lp.weight) over (order by lp.id) as cum
    from public.lucky_draw_prizes lp
    where lp.active and lp.weight > 0
      and (v_tier is null or lp.tier = v_tier)
  ) p
  where p.cum >= v_pick
  order by p.cum asc
  limit 1;

  -- (5) จ่ายรางวัล
  if v_prize.reward_type = 'coin' then
    insert into public.user_game_state (user_id, coin, updated_at)
    values (v_uid, greatest(v_prize.coin_amount, 0), now())
    on conflict (user_id) do update
      set coin = public.user_game_state.coin + greatest(v_prize.coin_amount, 0),
          updated_at = now();
  else
    insert into public.user_items (user_id, item_id, quantity)
    values (v_uid, v_prize.item_id, greatest(v_prize.item_qty, 1))
    on conflict (user_id, item_id) do update
      set quantity = public.user_items.quantity + greatest(v_prize.item_qty, 1);
    select * into v_item from public.shop_items where id = v_prize.item_id;
  end if;

  select coin into v_new_coin from public.user_game_state where user_id = v_uid;

  return json_build_object(
    'ok', true,
    'already_claimed', false,
    'tier', v_prize.tier,
    'reward_type', v_prize.reward_type,
    'coin_amount', v_prize.coin_amount,
    'item_id', v_prize.item_id,
    'item_qty', v_prize.item_qty,
    'item_name', v_item.name,
    'item_icon_url', v_item.icon_url,
    'item_effect_type', v_item.effect_type,
    'label', v_prize.label,
    'streak', v_streak,
    'guaranteed', v_guaranteed,
    'new_coin', v_new_coin
  );
end;
$$;

-- =====================================================================
-- 6) Seed รางวัลตั้งต้น (เฉพาะตอนตารางยังว่าง — รันซ้ำได้โดยไม่ซ้ำซ้อน)
--    รางวัล COIN ใส่ได้เสมอ / รางวัล item จะใส่ก็ต่อเมื่อมีไอเทมนั้นใน shop_items
-- =====================================================================
do $$
begin
  if not exists (select 1 from public.lucky_draw_prizes) then
    -- COIN — Common
    insert into public.lucky_draw_prizes (tier, reward_type, coin_amount, weight, label, sort_order) values
      ('common', 'coin', 10, 3, '10 เหรียญ', 1),
      ('common', 'coin', 20, 3, '20 เหรียญ', 2),
      ('common', 'coin', 30, 2, '30 เหรียญ', 3);
    -- COIN — Rare
    insert into public.lucky_draw_prizes (tier, reward_type, coin_amount, weight, label, sort_order) values
      ('rare', 'coin', 50, 3, '50 เหรียญ', 10),
      ('rare', 'coin', 80, 2, '80 เหรียญ', 11);
    -- COIN — Epic
    insert into public.lucky_draw_prizes (tier, reward_type, coin_amount, weight, label, sort_order) values
      ('epic', 'coin', 150, 2, '150 เหรียญ', 20),
      ('epic', 'coin', 300, 1, '300 เหรียญ (แจ็คพอต)', 21);

    -- item — Common (ยาฟื้นพลัง x1)
    insert into public.lucky_draw_prizes (tier, reward_type, item_id, item_qty, weight, label, sort_order)
      select 'common', 'item', id, 1, 2, name || ' x1', 4
      from public.shop_items where kind = 'item' and name = 'ยาฟื้นพลัง' limit 1;
    -- item — Common (นาฬิกาทราย x1)
    insert into public.lucky_draw_prizes (tier, reward_type, item_id, item_qty, weight, label, sort_order)
      select 'common', 'item', id, 1, 2, name || ' x1', 5
      from public.shop_items where kind = 'item' and name = 'นาฬิกาทราย' limit 1;
    -- item — Rare (โล่ป้องกัน x1)
    insert into public.lucky_draw_prizes (tier, reward_type, item_id, item_qty, weight, label, sort_order)
      select 'rare', 'item', id, 1, 2, name || ' x1', 12
      from public.shop_items where kind = 'item' and name = 'โล่ป้องกัน' limit 1;
    -- item — Rare (ระเบิดพลัง x1)
    insert into public.lucky_draw_prizes (tier, reward_type, item_id, item_qty, weight, label, sort_order)
      select 'rare', 'item', id, 1, 2, name || ' x1', 13
      from public.shop_items where kind = 'item' and name = 'ระเบิดพลัง' limit 1;
    -- item — Epic (โล่ป้องกัน x3)
    insert into public.lucky_draw_prizes (tier, reward_type, item_id, item_qty, weight, label, sort_order)
      select 'epic', 'item', id, 3, 1, name || ' x3', 22
      from public.shop_items where kind = 'item' and name = 'โล่ป้องกัน' limit 1;
    -- item — Epic (ระเบิดพลัง x3)
    insert into public.lucky_draw_prizes (tier, reward_type, item_id, item_qty, weight, label, sort_order)
      select 'epic', 'item', id, 3, 1, name || ' x3', 23
      from public.shop_items where kind = 'item' and name = 'ระเบิดพลัง' limit 1;
  end if;
end $$;
